[2025-04-16T06:07:51.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T06:07:51.165+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_advanced.model.dbt_lewagon.my_second_dbt_model scheduled__2025-04-15T00:00:00+00:00 [queued]>
[2025-04-16T06:07:51.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_advanced.model.dbt_lewagon.my_second_dbt_model scheduled__2025-04-15T00:00:00+00:00 [queued]>
[2025-04-16T06:07:51.180+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-16T06:07:51.202+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): model.dbt_lewagon.my_second_dbt_model> on 2025-04-15 00:00:00+00:00
[2025-04-16T06:07:51.220+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_advanced', 'model.dbt_lewagon.my_second_dbt_model', 'scheduled__2025-04-15T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/advanced/dbt_advanced.py', '--cfg-path', '/tmp/tmp0qhimsld']
[2025-04-16T06:07:51.222+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask model.dbt_lewagon.my_second_dbt_model
[2025-04-16T06:07:51.226+0000] {logging_mixin.py:190} WARNING - /root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=244) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-16T06:07:51.227+0000] {standard_task_runner.py:72} INFO - Started process 248 to run task
[2025-04-16T06:07:51.337+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_advanced.model.dbt_lewagon.my_second_dbt_model scheduled__2025-04-15T00:00:00+00:00 [running]> on host 9a8ef20dd1da
[2025-04-16T06:07:51.483+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_advanced' AIRFLOW_CTX_TASK_ID='model.dbt_lewagon.my_second_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T00:00:00+00:00'
[2025-04-16T06:07:51.485+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-16T06:07:51.509+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-16T06:07:51.509+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --models my_second_dbt_model --project-dir /app/airflow/dbt_lewagon']
[2025-04-16T06:07:51.524+0000] {subprocess.py:99} INFO - Output:
[2025-04-16T06:07:54.625+0000] {subprocess.py:106} INFO - [0m06:07:54  Running with dbt=1.9.1
[2025-04-16T06:07:57.111+0000] {subprocess.py:106} INFO - [0m06:07:57  Registered adapter: bigquery=1.9.0
[2025-04-16T06:07:57.883+0000] {subprocess.py:106} INFO - [0m06:07:57  Found 2 models, 4 data tests, 489 macros
[2025-04-16T06:07:57.886+0000] {subprocess.py:106} INFO - [0m06:07:57
[2025-04-16T06:07:57.887+0000] {subprocess.py:106} INFO - [0m06:07:57  Concurrency: 1 threads (target='dev')
[2025-04-16T06:07:57.887+0000] {subprocess.py:106} INFO - [0m06:07:57
[2025-04-16T06:07:59.128+0000] {subprocess.py:106} INFO - [0m06:07:59  1 of 1 START sql view model dbt_f***_day2_advanced.my_second_dbt_model ..... [RUN]
[2025-04-16T06:08:00.695+0000] {subprocess.py:106} INFO - [0m06:08:00  1 of 1 OK created sql view model dbt_f***_day2_advanced.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.56s]
[2025-04-16T06:08:00.748+0000] {subprocess.py:106} INFO - [0m06:08:00
[2025-04-16T06:08:00.749+0000] {subprocess.py:106} INFO - [0m06:08:00  Finished running 1 view model in 0 hours 0 minutes and 2.86 seconds (2.86s).
[2025-04-16T06:08:00.897+0000] {subprocess.py:106} INFO - [0m06:08:00
[2025-04-16T06:08:00.898+0000] {subprocess.py:106} INFO - [0m06:08:00  [32mCompleted successfully[0m
[2025-04-16T06:08:00.898+0000] {subprocess.py:106} INFO - [0m06:08:00
[2025-04-16T06:08:00.898+0000] {subprocess.py:106} INFO - [0m06:08:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-16T06:08:02.174+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-16T06:08:02.237+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-16T06:08:02.237+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_advanced, task_id=model.dbt_lewagon.my_second_dbt_model, run_id=scheduled__2025-04-15T00:00:00+00:00, execution_date=20250415T000000, start_date=20250416T060751, end_date=20250416T060802
[2025-04-16T06:08:02.267+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T06:08:02.311+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-16T06:08:02.313+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
